<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Waqas" failures="1" tests="6" name="com.qa.ninjatutorials.testcases.LoginTest" time="37.420" errors="0" timestamp="2024-08-15T09:47:30 EDT" skipped="0">
  <testcase classname="com.qa.ninjatutorials.testcases.LoginTest" name="verifyLoginWithNoCredentials" time="6.886"/>
  <system-out/>
  <testcase classname="com.qa.ninjatutorials.testcases.LoginTest" name="verifyInvalidEmailNoPassword" time="5.897"/>
  <system-out/>
  <testcase classname="com.qa.ninjatutorials.testcases.LoginTest" name="verifyValidEmailNoPassword" time="6.012"/>
  <system-out/>
  <testcase classname="com.qa.ninjatutorials.testcases.LoginTest" name="verifyValidEmailInvalidPassword" time="6.077"/>
  <system-out/>
  <testcase classname="com.qa.ninjatutorials.testcases.LoginTest" name="verifyLoginWithInvalidCredentials" time="5.827">
    <failure message="Expected warning message is not displayed. expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Expected warning message is not displayed. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at com.qa.ninjatutorials.testcases.LoginTest.verifyLoginWithInvalidCredentials(LoginTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredentials -->
  <system-out/>
  <testcase classname="com.qa.ninjatutorials.testcases.LoginTest" name="verifyLoginWithValidCredentials" time="6.721"/>
  <system-out/>
</testsuite> <!-- com.qa.ninjatutorials.testcases.LoginTest -->
